### ISSUE TITLE
Jest mocks resolution isn't working

### ISSUE THREAD

**Issue by winterdouglas** [software-mansion-labs/react-native-audio-api#1067]
### Description

Mock resolution fails in jest due to wrongly resolved paths:

`Cannot find module 'react-native-audio-api/mock' from 'jest.setup.js'`

I'm doing the configuration just as indicated in the docs:
```
jest.mock('react-native-audio-api', () =>
  require('react-native-audio-api/mock'),
);
```
I also tried to import it directly to see if it was something with my Jest configuration, but no luck.

By digging a bit I noticed that the `package.json` from the mocks folder, introduced in #925, seems to point to the wrong files by going up one extra directory:
```
{
  "main": "../../lib/module/mock/index",
  "module": "../../lib/module/mock/index",
  "react-native": "../../src/mock/index",
  "types": "../../lib/typescript/mock/index.d.ts"
}
```

Manually changing these paths to be only `../` worked on my project.

### Steps to reproduce

1. Add the described steps as per docs in `jest.setup.js`
```
jest.mock('react-native-audio-api', () =>
  require('react-native-audio-api/mock'),
);
```
2. Run the tests
3. It will right away fail with `Cannot find module 'react-native-audio-api/mock' from 'jest.setup.js'`

### Snack or a link to a repository

-

### React Native Audio API version

0.12.1

### React Native version

0.81.5

### Platforms

iOS

### JavaScript runtime

None

### Workflow

Expo Dev Client

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes
